import { createFileRoute } from "@tanstack/react-router";
import { LegalTemplate } from "@/components/marketing/LegalTemplate";
import { site } from "@/config/site";

export const Route = createFileRoute("/accessibility")({
  head: () => ({ meta: [{ title: `Accessibility — ${site.name}` }, { name: "description", content: "Montvelle's approach to accessible digital experiences, reasonable adjustments and member service." }] }),
  component: AccessibilityPage,
});

function AccessibilityPage() {
  return <LegalTemplate title="Accessibility statement" documentKey="accessibilityStatement" intro="Montvelle aims to make its public website, member-facing digital environment and service experience usable by as many people as reasonably possible, including people using keyboards, screen readers, zoom, high-contrast settings, voice input and other assistive technology. Accessibility is treated as an ongoing service responsibility rather than a one-time design exercise." sections={[
    { heading: "Our accessibility standard", body: "We use the Web Content Accessibility Guidelines (WCAG) 2.2 Level AA as the principal design and testing reference for Montvelle digital experiences. WCAG is an internationally recognised technical accessibility standard. Montvelle does not currently claim full WCAG 2.2 AA conformance for the entire website or private environment because a complete independent conformance audit has not yet been completed. Any future conformance claim will be made only for the scope actually tested and supported by evidence." },
    { heading: "What we design for", body: "Our design approach includes semantic page structure, logical heading order, keyboard-operable controls, visible focus states, meaningful form labels and error messages, sufficient text contrast, responsive layouts, text resizing and zoom, descriptive link text and useful alternative text where images convey information. Decorative imagery should not be necessary to understand or operate the page. Material new components and workflows should be reviewed for accessibility before release." },
    { heading: "Reasonable adjustments and accessible alternatives", body: "Where applicable law requires reasonable adjustments, Montvelle will consider and make reasonable changes needed to avoid placing a disabled person at a substantial disadvantage. This can include changing how a process is carried out, providing information in another accessible format, allowing an alternative communication route, giving additional assistance or using a different reasonable service method. We do not charge a disabled person an additional fee merely for a reasonable adjustment that the law requires us to provide." },
    { heading: "Tell us what works for you", body: "Members and applicants do not need to disclose more health or disability information than is reasonably necessary to explain an accessibility need. Where possible, tell us the barrier, the task you are trying to complete and the adjustment or format that would help. Accessibility information is handled under the Privacy Notice and should be shared only with people who need it to arrange the adjustment or provide the service." },
    { heading: "Private member and supplier areas", body: "Member, supplier and administrative tools should follow the same accessibility principles as the public website, with additional attention to authentication, forms, tables, dialogs, status messages, time-sensitive actions, Decision Rooms, file handling and error recovery. A private feature that cannot be used with a particular assistive technology should not be treated as the only route where a reasonable accessible alternative can be provided." },
    { heading: "Events, venues and in-person services", body: "Montvelle may coordinate gatherings, venues, travel, advisers and other in-person services. Accessibility needs for a venue or activity should be raised as early as reasonably possible so that access, seating, communication support, dietary or other relevant arrangements can be checked. Where an independently operated venue or supplier cannot reasonably meet a need, Montvelle will try to identify a reasonable alternative where one is available, but cannot guarantee that every third-party venue, destination or activity can accommodate every adjustment." },
    { heading: "Third-party websites and services", body: "Some journeys lead to independently operated websites, booking systems, advisers, payment institutions, venues or translation services. Those organisations control the accessibility of their own services. A link, introduction or booking does not make GSM responsible for the third party's digital accessibility, but if a third-party route creates a barrier to a Montvelle-coordinated service, tell us and we will consider a reasonable alternative or different coordination method where possible." },
    { heading: "Translation and readability", body: "Public copy is written to be as clear and concise as the subject permits. The language selector can provide machine-translated public pages through a third-party translation service. Machine translation may alter meaning, reading order, labels or assistive-technology behaviour and should not be treated as an accessibility substitute where a different format or human assistance is reasonably required. The English-language legal documents remain authoritative to the extent permitted by law." },
    { heading: "Known limitations and testing", body: "The site continues to evolve and some content, third-party resources or newly introduced components may contain accessibility barriers that have not yet been identified. Automated testing alone cannot establish WCAG conformance, so keyboard, screen-reader and other manual testing should be included in material accessibility reviews. Where we identify a significant barrier under our control, we aim to prioritise remediation according to user impact, legal obligation and operational risk." },
    { heading: "Reporting an accessibility problem", body: "If you encounter a barrier, use Contact Montvelle and select 'Accessibility', or use the official GSM contact details in the Legal Notice. Please identify the page or service, what you were trying to do, the technology or format involved where relevant, and the adjustment that would help. We will investigate and, where reasonably possible, provide an alternative route while the underlying issue is being addressed." },
    { heading: "Complaints and rights", body: "Accessibility concerns are reviewed as service matters and, where relevant, as requests for reasonable adjustment under applicable equality or disability law. Nothing in this statement limits a right to complain, bring a claim or contact a competent equality, consumer or regulatory body where the law gives that right. Raising an accessibility concern will not reduce a person's eligibility for membership or service merely because they are disabled or requested an adjustment." },
    { heading: "Continuous improvement", body: "Accessibility is reviewed as content, components, browsers, assistive technologies, member needs and applicable standards evolve. We may update this statement when testing scope, known limitations, standards or our service model materially changes. A future statement of full or partial WCAG conformance will identify the tested scope and basis for that claim." },
  ]} />;
}
