import { createFileRoute } from "@tanstack/react-router";
import { LegalTemplate } from "@/components/marketing/LegalTemplate";
import { site } from "@/config/site";

export const Route = createFileRoute("/accessibility")({
  head: () => ({ meta: [{ title: `Accessibility — ${site.name}` }, { name: "description", content: "Montvelle's approach to accessible digital experiences, reasonable adjustments and member service." }] }),
  component: AccessibilityPage,
});

function AccessibilityPage() {
  return <LegalTemplate title="Accessibility statement" documentKey="accessibilityStatement" intro="Montvelle aims to make its public website, member-facing digital environment and service experience usable by as many people as reasonably possible, including people using keyboards, screen readers, zoom, high-contrast settings, voice input and other assistive technology. Accessibility is treated as an ongoing and anticipatory service responsibility rather than a one-time design exercise or something considered only after a barrier is reported." sections={[
    { heading: "Our accessibility standard", body: "We use the Web Content Accessibility Guidelines (WCAG) 2.2 Level AA as the principal design and testing reference for Montvelle digital experiences. WCAG is an internationally recognised technical accessibility standard. Montvelle does not currently claim full WCAG 2.2 AA conformance for the entire website or private environment because a complete independent conformance audit has not yet been completed. Any future conformance claim will be made only for the scope actually tested and supported by evidence." },
    { heading: "What we design and test for", body: "Our design and testing approach includes semantic page structure, logical heading order, keyboard-operable controls, visible focus states that are not unnecessarily obscured, meaningful form labels and error messages, sufficient text contrast, responsive layouts, text resizing and zoom, descriptive link text, useful alternative text where images convey information, reasonable target sizes, accessible authentication and avoiding unnecessary repeated entry of information where the service can reasonably reuse it. Decorative imagery should not be necessary to understand or operate the page. Material new components and workflows should be reviewed for accessibility before release." },
    { heading: "Anticipatory reasonable-adjustment duty", body: "Where equality or disability law applies, Montvelle does not treat reasonable adjustments as something considered only after an individual complains. We aim to anticipate common barriers in advance and take reasonable steps to avoid substantial disadvantage for disabled people in the way a service, process, digital feature or membership activity is provided. Depending on the circumstances, this can include changing a policy or process, providing an auxiliary aid or accessible format, allowing another communication route, providing additional assistance, changing the way a service is delivered or arranging a reasonable alternative. What is reasonable depends on the circumstances, including effectiveness, practicality, safety, cost, resources and the nature of the service. We do not charge a disabled person an additional fee merely for a reasonable adjustment that the law requires us to provide." },
    { heading: "Tell us what works for you", body: "Members and applicants do not need to disclose more health or disability information than is reasonably necessary to explain an accessibility need. Where possible, tell us the barrier, the task you are trying to complete and the adjustment or format that would help. Accessibility information is handled under the Privacy Notice and should be shared only with people who need it to arrange the adjustment or provide the service." },
    { heading: "Private member and supplier areas", body: "Member, supplier and administrative tools should follow the same accessibility principles as the public website, with additional attention to authentication, forms, tables, dialogs, status messages, time-sensitive actions, Decision Rooms, file handling and error recovery. A private feature that cannot be used with a particular assistive technology should not be treated as the only route where a reasonable accessible alternative can be provided." },
    { heading: "Events, venues and in-person services", body: "Montvelle may coordinate gatherings, venues, travel, advisers and other in-person services. We aim to consider likely accessibility requirements when selecting or coordinating services and members should also raise any particular need as early as reasonably possible so that access, seating, communication support, dietary or other relevant arrangements can be checked. Where an independently operated venue or supplier cannot reasonably meet a need, Montvelle will consider reasonable steps within its own control, including identifying a reasonable alternative where one is available, but cannot guarantee that every third-party venue, destination or activity can accommodate every adjustment." },
    { heading: "Third-party websites and services", body: "Some journeys lead to independently operated websites, booking systems, advisers, payment institutions, venues or translation services. Those organisations control the accessibility of their own services. A link, introduction or booking does not make GSM responsible for every aspect of the third party's digital accessibility, but it does not remove any reasonable-adjustment duty that applies to Montvelle's own service. If a third-party route creates a barrier to a Montvelle-coordinated service, tell us and we will consider a reasonable alternative or different coordination method where possible." },
    { heading: "Translation and readability", body: "Public copy is written to be as clear and concise as the subject permits. The language selector can provide machine-translated public pages through a third-party translation service. Machine translation may alter meaning, reading order, labels or assistive-technology behaviour and should not be treated as an accessibility substitute where a different format or human assistance is reasonably required. The English-language legal documents remain authoritative to the extent permitted by law." },
    { heading: "Known limitations and testing", body: "The site continues to evolve and some content, third-party resources or newly introduced components may contain accessibility barriers that have not yet been identified. Automated testing alone cannot establish WCAG conformance, so keyboard, screen-reader and other manual testing should be included in material accessibility reviews. Where we identify a significant barrier under our control, we aim to prioritise remediation according to user impact, legal obligation and operational risk, and to provide a reasonable alternative route where practicable while remediation is under way." },
    { heading: "Reporting an accessibility problem", body: "If you encounter a barrier, use Contact Montvelle and select 'Accessibility', or use the official GSM contact details in the Legal Notice. Please identify the page or service, what you were trying to do, the technology or format involved where relevant, and the adjustment that would help. We will investigate and, where reasonably possible, provide an alternative route while the underlying issue is being addressed." },
    { heading: "Complaints and rights", body: "Accessibility concerns are reviewed as service matters and, where relevant, as requests for reasonable adjustment under applicable equality or disability law. Nothing in this statement limits a right to complain, bring a claim or contact a competent equality, consumer or regulatory body where the law gives that right. Raising an accessibility concern will not reduce a person's eligibility for membership or service merely because they are disabled or requested an adjustment." },
    { heading: "Continuous improvement", body: "Accessibility is reviewed as content, components, browsers, assistive technologies, member needs and applicable standards evolve. We aim to record and review significant accessibility barriers and reasonable adjustments so recurring issues can inform future design and service decisions. We may update this statement when testing scope, known limitations, standards or our service model materially changes. A future statement of full or partial WCAG conformance will identify the tested scope and basis for that claim." },
  ]} />;
}
