import { createFileRoute } from "@tanstack/react-router";
import { LegalTemplate } from "@/components/marketing/LegalTemplate";
import { site } from "@/config/site";

export const Route = createFileRoute("/confidentiality")({
  head: () => ({ meta: [{ title: `Confidentiality & No Solicitation — ${site.name}` }, { name: "description", content: "The confidentiality, consent and no-solicitation standard that protects Montvelle member spaces, introductions, Decision Rooms and private matters." }] }),
  component: ConfidentialityPage,
});

function ConfidentialityPage() {
  return <LegalTemplate title="Confidentiality & No Solicitation" documentKey="confidentiality" intro="Montvelle works only if members can bring the real issue into the room without turning private life, family context or trusted relationships into a commercial asset. This standard applies alongside the Membership Agreement, Website Terms, Privacy Notice and, where relevant, the Supplier & Partner Agreement." sections={[
    { heading: "Scope and who must comply", body: "This standard applies to members, approved household users, delegates, guests, applicants and other people given access to a Montvelle private space or confidential Montvelle material. Suppliers, specialists, contractors and staff are also subject to confidentiality duties under their applicable agreements, policies or professional obligations. A Member is responsible for taking reasonable steps to ensure that a guest or delegate they invite understands the confidentiality rules that apply to that participation." },
    { heading: "What counts as Confidential Information", body: "Confidential Information includes any non-public information disclosed through or because of Montvelle that a reasonable person would understand to be private, restricted or commercially sensitive. This includes another person's identity or membership status where not public; contact details; family, household, health, security or travel circumstances; ownership, wealth, business, investment or philanthropic context; legal, tax, immigration, banking or adviser information; Table discussions; requests and briefs; Decision Room content; messages; private invitations and venue details; photographs or recordings from private settings; provider or sourcing intelligence that is not public; and any material marked or clearly communicated as confidential." },
    { heading: "What is not Confidential Information", body: "Information is not treated as Confidential Information to the extent the recipient can reasonably demonstrate that it was already lawfully known to them without a duty of confidence, becomes public through no breach of duty, is received lawfully from an independent third party without a confidentiality restriction, or is independently developed without using Montvelle Confidential Information. A person's private facts do not become non-confidential merely because fragments can be found separately online." },
    { heading: "Use only for the reason it was shared", body: "Confidential Information may be used only for the Montvelle matter, relationship, introduction, event or decision for which access was given, or for another purpose expressly authorised by the person concerned. It must not be repurposed for marketing, prospecting, competitive intelligence, media activity, list-building, recruitment, fundraising, investment solicitation, database enrichment, background dossiers or any unrelated commercial or personal advantage." },
    { heading: "Member identity and membership status", body: "Do not disclose, confirm or imply that another person is a Montvelle member, applicant, guest, participant or client unless that person has made the relationship public or has consented to the disclosure. The same rule applies to attendance at a private Montvelle event, participation in a Table, use of a Decision Room and the existence of a confidential request or introduction." },
    { heading: "Household and Decision Room boundaries", body: "Family membership does not erase privacy between adults. One adult household member's messages, requests, adviser context or Decision Rooms must not be disclosed to another adult merely because they share a household membership. Delegates and external participants receive only the matter-specific access authorised for them. Information seen in one Decision Room must not be carried into another matter, another household relationship or another professional engagement without authority." },
    { heading: "No recording, copying or AI ingestion by default", body: "Private sessions, screens, messages, documents and conversations must not be recorded, transcribed, photographed, screenshotted, copied, bulk-exported, forwarded, uploaded to a public or general-purpose AI service, used to train an external model or otherwise reproduced beyond what is reasonably needed for the authorised Montvelle purpose unless the people concerned have clearly agreed or a non-waivable legal right requires it. Personal notes should contain no more confidential detail than reasonably necessary and must be protected appropriately." },
    { heading: "Introductions and contact details", body: "Montvelle introductions are consent-led. Contact details, private profiles and sensitive context are released only where the intended participants have agreed or another lawful basis applies. Receiving an introduction does not create a right to disclose that person's details to colleagues, assistants, investors, recruiters, marketers or other third parties. A relationship formed after an introduction may of course continue directly if the parties choose; this standard does not require a member to route ordinary ongoing dealings with an introduced adviser or supplier through Montvelle." },
    { heading: "No solicitation and no harvesting", body: "Montvelle is not a prospecting environment. During membership or authorised access, and for 12 months after it ends, a person must not use another member's identity or contact details learned solely through Montvelle to make unsolicited targeted approaches for goods or services, employment or recruitment, investment, fundraising, sponsorship, political campaigning or other commercial solicitation. This does not prohibit a genuine communication requested or consented to by the recipient, a pre-existing relationship that was not obtained through Montvelle, ordinary social contact, or non-targeted public advertising that does not use Montvelle-derived information. Member or provider details must never be scraped, compiled, sold, licensed, exchanged or repackaged as a contact list or commercial database." },
    { heading: "No misuse of Montvelle introductions or relationships", body: "A person must not misrepresent a Montvelle introduction as an endorsement, use another member's name to obtain access or credibility without permission, or claim that Montvelle, GSM or another member supports an investment, transaction, campaign, business or provider without express authority. Nothing here prevents a member from directly instructing an introduced professional or buying from an introduced supplier for the member's own purposes; the restriction is on misuse of private access and relationship intelligence, not legitimate engagement." },
    { heading: "Guests, assistants and delegates", body: "A member who asks an assistant, family-office representative, household delegate or guest to participate should limit that person's access to what they actually need. The invited person must not assume that access to one matter creates access to the wider household or membership. If authority changes, the Member or authorised principal should tell GSM promptly so access can be reduced or withdrawn." },
    { heading: "Permitted professional and internal disclosure", body: "A person may disclose Confidential Information to their own lawyer, tax adviser, accountant, insurer or other professional adviser where that disclosure is reasonably necessary and the recipient is subject to an appropriate duty of confidence. A business or family-office Member may disclose on a strict need-to-know basis to authorised personnel who require the information for the relevant matter and are bound by confidentiality obligations. The disclosing person remains responsible for avoiding unnecessary onward disclosure." },
    { heading: "Legal, regulatory, safeguarding and emergency disclosures", body: "Nothing in this standard prevents a disclosure required by law, court order, regulator or competent authority, or a disclosure reasonably necessary to report crime, fraud, abuse, harassment, safeguarding risk, a serious safety concern or professional misconduct. Where legally permitted and sensible, a person required to make a compulsory disclosure should limit it to what is required and notify GSM or the affected person so protective steps can be considered. This standard must never be used to silence a lawful whistleblower, regulator, police report or good-faith safeguarding disclosure." },
    { heading: "Montvelle's own confidentiality obligations", body: "GSM treats member identity, household context, requests and private relationship information as restricted information. Access should be limited by role and matter, suppliers and specialists should receive only the minimum context reasonably needed for authorised work, and staff and contractors should be subject to appropriate confidentiality and security obligations. GSM may preserve or disclose information where required for law, safety, fraud prevention, legal claims or another basis described in the Privacy Notice." },
    { heading: "If a breach is suspected", body: "Anyone who becomes aware of a suspected loss, unauthorised disclosure, screenshot, forwarding, account compromise or other confidentiality breach should notify Montvelle promptly through the secure contact route and take reasonable steps to contain the issue. Relevant material and evidence should be preserved where needed for investigation. GSM may temporarily restrict access, reset credentials, withdraw a participant from a matter or take other proportionate protective steps while the issue is assessed." },
    { heading: "Return, deletion and continued access", body: "When access to a matter ends, confidential copies that are no longer reasonably needed for an authorised purpose should be deleted or securely returned, subject to legal, regulatory, insurance, professional-record or legitimate dispute-retention requirements. Ending membership does not create a right to keep exported member lists, private profiles, Decision Room materials or confidential contact intelligence for future use." },
    { heading: "Complaints, reviews and lawful criticism", body: "This standard does not prevent a person from making a truthful good-faith complaint about Montvelle, a member, supplier or professional; obtaining legal advice; contacting an insurer, ombudsman, regulator, court or law-enforcement body; exercising a statutory consumer or employment right; or making a protected disclosure. What remains prohibited is the unnecessary publication of another person's confidential information, knowing falsehoods, harassment, doxxing or using a complaint as a pretext to expose unrelated private material." },
    { heading: "Enforcement and remedies", body: "A serious or repeated breach may be treated as a material breach of the applicable Membership Agreement, Website Terms, Supplier & Partner Agreement or access conditions and may justify removal from an event or matter, restricted access, suspension or termination. Because misuse or disclosure of highly private information may cause harm that cannot be adequately repaired by money alone, GSM or an affected person may seek injunctive or other equitable relief where legally available, in addition to other lawful remedies. Financial liability, indemnities and liability limits remain governed by the applicable contract and mandatory law; this standard does not create a punitive charge or override non-waivable rights." },
    { heading: "How long these duties continue", body: "Confidentiality duties continue after access, membership or a particular matter ends for as long as the information remains confidential by its nature. Obligations relating to passwords, security arrangements, private family or health information, trade secrets and non-public legal or financial matters may therefore continue indefinitely while the information remains non-public. The targeted no-solicitation restriction above lasts 12 months after membership or authorised access ends. Obligations end to the extent information genuinely falls within one of the exclusions stated above." },
    { heading: "Relationship with other Montvelle documents", body: "This standard is incorporated into the paid membership contractual framework and is accepted alongside the Membership Agreement, Website Terms and Privacy Notice. The Membership Schedule and Membership Agreement govern any conflict affecting a paid membership. Suppliers and specialists are also subject to their separate Supplier & Partner Agreement or professional engagement where applicable. Privacy rights, data-handling obligations and mandatory legal rights remain governed by applicable law and the Privacy Notice." },
  ]} />;
}
