import { createFileRoute } from "@tanstack/react-router";
import { LegalTemplate } from "@/components/marketing/LegalTemplate";
import { site } from "@/config/site";

export const Route = createFileRoute("/cookies")({
  head: () => ({ meta: [{ title: `Cookies — ${site.name}` }, { name: "description", content: "How Montvelle uses cookies, browser storage, security technologies and third-party translation resources." }] }),
  component: CookiesPage,
});

function CookiesPage() {
  return <LegalTemplate title="Cookies & local storage" documentKey="cookies" intro="Montvelle uses a deliberately restrained technology stack. We currently do not use advertising pixels, cross-site behavioural tracking or non-essential analytics cookies on the public Montvelle site. This notice explains the limited cookies and browser-storage technologies that are used or may be loaded when a user asks for a particular function." sections={[
    { heading: "What this notice covers", body: "Cookie rules apply not only to traditional cookies but also to technologies that store information on, or access information from, a browser or device. This can include local storage, session storage, authentication/session tokens, security identifiers and some third-party scripts. Server-side logs that do not store or read information from the user's device are covered by the Privacy Notice rather than by this cookie notice." },
    { heading: "Current Montvelle position", body: "The public site is not designed around advertising technology. Montvelle does not currently activate advertising pixels, cross-site behavioural tracking, retargeting tags or non-essential web-analytics cookies. We do not sell browsing data or use site visits to build third-party advertising audiences. If that position changes, any storage or access technology requiring consent will not be enabled for affected users until the legally required information and choice mechanism are in place." },
    { heading: "Strictly necessary authentication and security storage", body: "Private member, supplier and administrative functions may use session or browser storage, tokens and identifiers that are necessary to authenticate a user, preserve security state, enforce access boundaries, prevent misuse, record an explicit security choice or keep a requested online function working. These technologies are limited to operational/security purposes and are not used for advertising. Blocking necessary session or security storage can prevent sign-in, protected forms or private functions from working correctly." },
    { heading: "Cloudflare Turnstile security checks", body: "Protected Montvelle forms can load Cloudflare Turnstile when a production Turnstile site key is configured. Turnstile runs security challenges in the browser to distinguish legitimate users from automated abuse and produces a short-lived verification token. Cloudflare may process browser, device, network and challenge signals and may use technical storage depending on its configuration. Montvelle uses Turnstile only for security and fraud/abuse prevention, not for advertising or behavioural marketing. Form-field content is not supplied to Turnstile by the Montvelle widget itself. Cloudflare operates under its own privacy and security terms." },
    { heading: "Language preference: googtrans", body: "Montvelle's public language selector starts in English and does not load Google Translate merely because a visitor opens the site. If the visitor actively chooses a non-English language, Montvelle writes a first-party `googtrans` preference so the browser can apply and remember that choice, then loads Google's translation resources. The Montvelle-set preference is used only for the requested translation/appearance function and is not used by Montvelle for advertising or profiling. Choosing English clears the Montvelle `googtrans` preference." },
    { heading: "Google Translate third-party technology", body: "After a visitor chooses a translated language, Google Translate resources are loaded into the page. Google may receive technical information and may set or access its own cookies or similar technologies under Google's terms and privacy practices. Montvelle does not load Google Translate resources while the site remains in English. Translation is a user-selected convenience; the English-language Montvelle legal documents remain authoritative to the extent permitted by law." },
    { heading: "Browser local storage in preview and review environments", body: "Internal preview and review environments may use browser local storage for preview access state, test applications or messages, supplier/member preview records and preview evidence of legal-document acceptance. These records remain on the particular browser/device unless cleared or overwritten and are not a substitute for a production audit or intake system. Production member, supplier, contact and legal-acceptance records must be persisted through the approved production systems rather than relying on browser-only preview storage." },
    { heading: "User preferences and appearance", body: "Where Montvelle stores a setting because the user has actively selected how the service should appear or function — for example a language choice — that storage is used only to provide or remember the requested preference. Where applicable law treats that storage as exempt because it is necessary for the user-requested function or appearance, no separate cookie consent is required; where consent is required, the choice will be obtained before the non-essential storage is used." },
    { heading: "No hidden consent through continued browsing", body: "Montvelle does not treat merely continuing to browse the website as consent to non-essential tracking. If a future analytics, advertising or other non-essential technology requires consent, the user must be given clear information and an appropriate positive choice before it is activated. Refusing such optional technology must not block access to the core public site unless the technology is genuinely necessary for the specific function requested." },
    { heading: "Third-party links and independent services", body: "A link from Montvelle to a hotel, adviser, venue, payment institution, professional firm or other independent service does not cause Montvelle to control the cookies used after the user leaves Montvelle. Those third parties apply their own cookie and privacy practices. Where a third-party service is embedded directly into Montvelle, it will be assessed and disclosed according to the function it performs and the law that applies." },
    { heading: "How to control or clear storage", body: "Browsers generally allow users to view, block, delete or restrict cookies and local storage, and to block third-party cookies. Clearing the `googtrans` cookie returns Montvelle to English. Clearing authentication or security storage may sign a user out or require a security check again. Clearing browser-only preview records permanently removes those local preview records from that device. Browser private/incognito modes can also limit persistence, subject to the browser's own behaviour." },
    { heading: "Cookie and storage reviews", body: "Montvelle should maintain an inventory of storage/access technologies actually deployed, including whether each is first- or third-party, session or persistent, its purpose, duration and legal/consent status. A material technology change — particularly analytics, advertising, social tracking, fingerprinting or a new embedded third party — must be privacy-reviewed before deployment and this notice and any consent controls updated first." },
    { heading: "Changes to this notice", body: "The current version and effective date are shown on this page. We may update the notice when the technologies used by Montvelle change. A notice update does not by itself authorise a new non-essential tracker: where consent is legally required for the technology, the required consent mechanism must be in place before that technology is activated." },
  ]} />;
}
