import { createFileRoute } from "@tanstack/react-router";
import { LegalTemplate } from "@/components/marketing/LegalTemplate";
import { site } from "@/config/site";

export const Route = createFileRoute("/legal")({
  head: () => ({ meta: [{ title: `Legal notice — ${site.name}` }, { name: "description", content: "Corporate, regulatory and legal information for Montvelle." }] }),
  component: LegalNoticePage,
});

function LegalNoticePage() {
  return <LegalTemplate title="Legal notice" documentKey="legalNotice" intro={`${site.name} is a brand and service operated by ${site.operator}, a Delaware limited liability company. This notice identifies the operator, official contact details and the legal character of the Montvelle service. It should be read with the Membership Agreement, Website Terms, Privacy Notice and other documents that apply to a particular relationship.`} sections={[
    { heading: "Operator and corporate identity", body: "Montvelle is operated by Global Solutions Management LLC, a limited liability company organised under the laws of the State of Delaware, United States. Company number: CRN 10420698. Registered office and address for service: 16192 Coastal Highway, Lewes, Delaware 19958, United States. Montvelle is a trading brand of GSM and is not a separate legal person." },
    { heading: "Electronic contact", body: "GSM can be contacted through Contact Montvelle and at contact@global-solutions-management.com. The email address is provided as an official business contact route for company, contractual and legal enquiries. Do not send passwords, full payment-card details or unnecessary sensitive information by email. Where a Membership Schedule, invoice, assignment or formal correspondence gives a more specific notice address or method for a particular contract, that method should be used for that contractual notice." },
    { heading: "Contracting entity and document precedence", body: "Unless a written Membership Schedule, assignment, invoice or other agreement expressly identifies another contracting party, Global Solutions Management LLC is the operator and contracting entity for Montvelle membership and Montvelle-supplied services. For paid membership, the Membership Schedule, Membership Agreement and incorporated Website Terms determine the contractual relationship and their stated order of precedence applies. This public notice does not override a signed or expressly accepted contract or a mandatory legal right." },
    { heading: "Nature of the service", body: "Montvelle is a private membership, community, research, sourcing, coordination and lifestyle service. It may facilitate peer relationships, gatherings, consent-led introductions, Expert Councils, Decision Rooms, concierge coordination, family participation and private-office tools. GSM does not become a law firm, investment adviser, broker-dealer, tax adviser, medical provider, immigration adviser, fiduciary, trustee, insurer or other regulated professional merely by providing membership, information, research, introductions or coordination." },
    { heading: "Independent professionals and suppliers", body: "Lawyers, accountants, investment professionals, medical professionals, immigration advisers, fiduciaries, property specialists, educators, travel providers and other external specialists or suppliers remain independent unless a written agreement expressly states otherwise. Their licences, professional duties, engagement terms, fees, advice, goods and services remain their responsibility. Montvelle sourcing, checking, introducing or coordinating a third party is not a guarantee of that party's performance or an adoption of its professional advice." },
    { heading: "No partnership, fiduciary duty or agency", body: "Membership, attendance at a gathering, participation in a Table, introduction, Circle, Expert Council or Decision Room does not by itself create a partnership, joint venture, fiduciary relationship, employment relationship, franchise or agency between GSM and a member, guest, supplier, specialist or other third party. No person may bind GSM or a member unless express written authority has been given for the particular matter." },
    { heading: "No public investment or regulated offer", body: "Nothing on this website is an offer of securities, investment advice, a solicitation to invest, a public fundraising solicitation, a regulated financial promotion or a guarantee of access to any investment or transaction. Any investment, financing or other regulated opportunity must be considered separately through appropriately authorised parties and under the law that applies to it." },
    { heading: "Third-party names, marks and references", body: "References to hotels, schools, venues, advisers, firms, institutions, destinations, brands or other third parties are descriptive unless an express partnership or formal relationship is stated. Their names, marks and materials remain the property of their respective owners. A reference, link, sourcing record or introduction does not by itself mean that the third party endorses Montvelle or that GSM endorses every product, service or statement of that third party." },
    { heading: "Montvelle intellectual property", body: "The Montvelle name, monogram, visual identity, website design, software, private frameworks, editorial content and original materials are owned by or licensed to Global Solutions Management LLC unless stated otherwise. No public access to the website grants a licence to reproduce, scrape, republish, reverse engineer, commercialise, train a model on, or create confusingly similar branding or products except where a non-waivable legal right permits it." },
    { heading: "Confidential and member-only information", body: "Private member areas, member identities where not public, introductions, Decision Rooms, family and household information, ownership and adviser context, private venue details and confidential correspondence are not public materials. Access is limited to the intended relationship and is governed by the Membership Agreement, Confidentiality & No Solicitation standard, Privacy Notice and any assignment-specific restrictions. Public availability of a person's name elsewhere does not make private Montvelle context about that person public." },
    { heading: "Complaints and service enquiries", body: "Questions about membership, service quality, supplier coordination, billing, cancellation or a legal issue should be raised through the relevant Contact Montvelle category or the official business email above. Where the complaint concerns an independent professional or supplier, that party's own contractual, professional, regulatory or insurance complaints route may also apply. Raising a complaint with Montvelle does not transfer the third party's professional responsibility to GSM." },
    { heading: "Privacy, cookies and electronic communications", body: "Personal information is handled under the Privacy Notice and applicable law. Cookies, local storage and similar browser technologies are described in the Cookies & local storage notice. Operational and legal communications may be sent electronically where the applicable contract and law permit. Montvelle does not publish member data or sell access to member identities." },
    { heading: "Translations", body: "Public pages may be translated using a third-party translation service for convenience. Machine translation can alter nuance or legal meaning. The English-language Montvelle legal and contractual documents are authoritative to the extent permitted by applicable law; where mandatory local law gives another-language version priority, that law applies." },
    { heading: "Mandatory rights and local law", body: "Nothing in this notice excludes, restricts or misstates a consumer, privacy, statutory, regulatory or other right that cannot lawfully be waived. Montvelle is international, so mandatory rules may apply because of a member's residence, the place a service is supplied, the nature of a professional service or another connecting factor even where a contract chooses Delaware law." },
    { heading: "Formal notices and service", body: "For general legal and company correspondence, use the registered office, Contact Montvelle or contact@global-solutions-management.com. A formal notice concerning a specific membership, supplier assignment or other contract must follow any notice clause or address stated in that contract or in formal correspondence for that relationship. GSM may verify the sender's identity or authority before disclosing confidential information or acting on an instruction." },
  ]} />;
}
