import { createFileRoute } from "@tanstack/react-router";

import { LegalTemplate } from "@/components/marketing/LegalTemplate";
import { familyMembershipPricing, membershipPricing } from "@/config/membershipPricing";
import { site } from "@/config/site";

export const Route = createFileRoute("/membership-agreement")({
  head: () => ({
    meta: [
      { title: `Membership Agreement — ${site.name}` },
      {
        name: "description",
        content:
          "The Montvelle Membership Agreement governing paid membership with Global Solutions Management LLC.",
      },
    ],
  }),
  component: MembershipAgreementPage,
});

function MembershipAgreementPage() {
  return (
    <LegalTemplate
      title="Membership Agreement"
      documentKey="membershipAgreement"
      intro={`This Membership Agreement governs paid Montvelle membership supplied by ${site.operator}, a Delaware limited liability company ("GSM"). It forms part of the contract between GSM and the approved individual, family office, family entity, company or other member identified in the applicable Membership Schedule. The Website Terms, Privacy Notice and Confidentiality & No Solicitation standard accepted with the membership are incorporated into that contractual framework. Where documents conflict, the Membership Schedule prevails for that membership, followed by this Agreement, then the Website Terms, except where mandatory law requires another result.`}
      sections={[
        {
          heading: "1. Membership and acceptance",
          body: "Montvelle is a private global membership community, coordination and private-service membership. Membership may include curated peer relationships and Tables, private gatherings, member introductions, knowledge resources, Global Life coordination, Concierge and Private Office coordination, family learning, member technology and other services made available to the relevant membership. Payment does not compel GSM to admit an applicant. GSM may conduct identity, sanctions, fraud, safety, suitability and other checks reasonably required to protect the community or comply with law. Membership becomes active only when GSM has accepted the purchaser, the applicable contractual documents have been accepted, required checks have been completed, commencement amounts have cleared and — where a statutory cooling-off period applies to that purchaser — either that period has expired or the purchaser has made a separate express request for the service to begin sooner. If GSM declines an unactivated paid membership, GSM will arrange return of the membership and admission fees paid for that unactivated membership, subject to applicable law.",
        },
        {
          heading: "2. Individual and family membership; household access",
          body: "Montvelle applies one standard of membership, offered either as an individual membership held by one approved principal member, or as a family membership held as a household relationship in which more than one approved adult may use Montvelle independently. Family membership is not a higher or lower level of Montvelle and is not account sharing. The approved household composition, including any approved adult household members, age-appropriate next-generation participation and any authorised household delegate, is subject to GSM approval and is recorded in the Membership Schedule. Each approved person is issued their own login; login credentials may not be shared. Membership may not be sold, transferred, sublicensed or used to provide access to an unauthorised person without GSM's prior written consent. Delegated access granted to an assistant, family-office representative or household delegate is delegated access to identified matters only and does not itself constitute Montvelle membership. Personal matters, requests and messages belonging to an approved adult are not automatically visible to the Household Principal or to any other household user; sharing within a household occurs only where that person or the Membership Schedule so provides. The Member remains responsible for ensuring that authorised users comply with this Agreement and all applicable Montvelle policies.",
        },
        {
          heading: "2A. Consumer and business purchasing capacity",
          body: "The Membership Schedule records whether the contracting Member is purchasing principally as an individual consumer or for the purposes of a business, family office, company, trust, partnership or other entity. A business or entity Member warrants that it is contracting for business or organisational purposes and that the person accepting these terms has authority to bind it. Consumer protections that apply only to consumers do not apply to a business or entity purchase unless mandatory law provides otherwise. Nothing in this Agreement removes a right that cannot lawfully be excluded because of the Member's true contracting capacity or place of residence.",
        },
        {
          heading: "3. Term and renewal",
          body: "Unless the Membership Schedule states otherwise, membership runs for a fixed 12-month term from the agreed activation date. The annual membership is a single annual commitment and is not a month-to-month service, a series of monthly purchases or a pay-per-request arrangement. Membership cannot be paused, frozen or carried forward merely because it is not used. Montvelle membership does not automatically renew at launch. Before expiry, GSM may invite the Member to renew at the then-current price and on the then-current renewal terms. A previous price does not create a right to a future or grandfathered price. A renewal becomes binding only when the renewal terms are accepted and the applicable renewal fee is paid, unless a later Membership Schedule expressly provides another lawful renewal mechanism.",
        },
        {
          heading: "4. Fees and payment",
          body: `The current ${membershipPricing.pricingYear} individual founding price is ${membershipPricing.annualDisplay} for a 12-month membership, paid in advance, plus a one-time ${membershipPricing.joiningDisplay} admission and onboarding fee, giving a first-year total of ${membershipPricing.firstYearDisplay} before applicable taxes and separately purchased third-party goods or services. Family membership is published as a "from" price of ${familyMembershipPricing.fromAnnualAmountDisplay} for a 12-month household membership; the final annual fee, the approved household composition and any admission or onboarding amount for a family membership are determined after review and recorded in the Membership Schedule. The annual fee is consideration for reserving access to Montvelle, service capacity, coordination infrastructure, member technology and the membership relationship throughout the term; it is not apportioned by the number of requests made, benefits used or months in which the Member actively uses the service. The contractual amount for a Member is the amount stated in the payment instructions, invoice or Membership Schedule issued to that Member. Fees are settled by bank transfer against instructions and a payment reference issued privately after admission and acceptance of this Agreement and the Membership Schedule; GSM does not operate an online card checkout and does not publish account details. GSM may change prices for future new memberships and renewals. Taxes, duties, levies, payment charges, bank charges and similar amounts are payable as stated and as required by law. Where GSM agrees a different billing currency, the fixed contractual amount is stated in the applicable payment instructions, invoice or Membership Schedule.`,
        },
        {
          heading: "4A. Who sells and who performs",
          body: "GSM sells, operates and performs the Montvelle membership and services described in this Agreement. There is no third-party seller of record and no online card checkout for Montvelle membership. Membership is requested, reviewed and, if accepted, settled by bank transfer against payment instructions issued privately to the Member. Nothing in this clause reduces any mandatory consumer right.",
        },
        {
          heading: "5. Third-party costs",
          body: "Travel, accommodation, aviation, transport, event tickets, venues, restaurants, property, healthcare, education, professional advice and other externally supplied goods and services are separate from the Montvelle membership fee unless the Membership Schedule expressly states otherwise. Third-party suppliers may require deposits, prepayment, cancellation fees, insurance or other charges. Those costs are the Member's responsibility where the Member authorises the purchase or instruction. Cancellation or termination of Montvelle membership does not cancel, unwind or transfer liability for a separate third-party contract, and GSM is not required to fund a third-party refund from its own resources while a supplier dispute or recovery remains outstanding.",
        },
        {
          heading: "6. Cancellation, cooling-off and annual-fee refunds",
          body: "Nothing in this Agreement removes a cancellation, refund or consumer right that cannot lawfully be waived. Where a statutory cooling-off right applies and the Member does not separately and expressly request that onboarding, service preparation or services begin during that period, GSM will not begin the relevant consumer service until the cooling-off period has expired. Acceptance of this Agreement, the Membership Schedule or any other contractual document is not an early-start request, and neither is payment; an early-start request is a separate express request and is never assumed. Where the Member expressly asks GSM to begin before that period expires and then cancels within it, GSM may deduct the value of services properly supplied before cancellation to the extent applicable law permits. Once any applicable cooling-off period has expired, the 12-month annual commitment stands. A Member may ask to stop using or receiving the service before the end of the term, but voluntary early cancellation, non-use, dissatisfaction, a change of mind, or a change in personal, family, business, financial, travel or residence circumstances does not create a contractual right to a refund, credit, pause or pro-rata repayment of the annual Membership Fee. To the fullest extent permitted by law, the admission and onboarding fee is also non-refundable once the relevant admission or onboarding work has been performed or committed. The only contractual exceptions after the cooling-off period are where the Membership Schedule expressly provides otherwise, mandatory law requires a refund, or GSM terminates without Member fault or permanently withdraws substantially all core Montvelle membership services without a reasonable substitute. In those latter GSM-fault or withdrawal cases, any contractual refund is limited to the unearned pro-rata portion of the annual Membership Fee from the effective termination date; admission/onboarding amounts already earned, taxes already accounted for where non-recoverable, and authorised third-party or non-recoverable costs are excluded to the extent permitted by law.",
        },
        {
          heading: "7. How provider service works: request-led, not a directory",
          body: "Montvelle is request-led. There is no member-facing directory, catalogue, marketplace or browsable list of suppliers, providers or experts, and membership does not grant a right to browse or contact providers directly through Montvelle. Where a Member describes a need, GSM researches, sources, checks, coordinates and, where appropriate, introduces external organisations, firms or individual experts in response to that specific need. Any sourcing, credential check, reference check, reputation check, professional-directory check or other diligence performed by GSM is a reasonable coordination step only; it is not an audit, certification, warranty, guarantee of competence, guarantee of financial standing or promise of future performance, and unless GSM expressly agrees otherwise in writing it does not create a continuing duty to monitor a provider after introduction. Unless GSM expressly agrees in writing to act as the supplier or principal, the relevant third party — not GSM — supplies those goods, professional advice or services and is responsible for its own acts, omissions, licences, professional duties, terms and performance. The Member decides whether to instruct or transact with a third party and remains responsible for appropriate due diligence. GSM does not guarantee reservations, upgrades, aviation, event access, school places, visas, immigration outcomes, transactions, investments, property results, medical outcomes, professional outcomes, introductions or any other third-party result.",
        },
        {
          heading: "7A. Ask Montvelle and the 24-hour response standard",
          body: "A Member may ask Montvelle for anything within the scope of their membership. GSM aims to acknowledge a request promptly and to provide a meaningful first response within 24 hours of receiving it — an answer, a considered update, a set of checked options or a clear statement of what happens next and when. This is a response standard, not a promise of fulfilment, delivery, resolution, booking, availability or outcome within 24 hours. Response and delivery times can legitimately be affected by complexity, time zones and geography, third-party availability, regulated or professional processes, seasonal demand, emergencies, safeguarding matters and compliance or verification requirements. Emergency or safety-critical matters should be raised with the appropriate emergency services or a qualified professional first; Montvelle is not an emergency service.",
        },
        {
          heading: "7B. Expert Councils",
          body: "An Expert Council is an on-demand, member-specific group of independent specialists assembled by GSM around a particular decision or matter raised by the Member. Expert Councils are not standing committees, panels, boards or an existing directory, and no Expert Council exists before a Member's need calls for one. GSM may research worldwide to identify suitable specialists and is not limited to any existing roster. Where the nature of the matter calls for regulated or professional advice, the relevant specialist should be separately instructed by the Member under that specialist's own engagement terms, professional duties and insurance arrangements. Specialists remain independent of GSM and of one another. GSM does not supervise their professional judgement, does not guarantee that their licences, insurance or circumstances will remain unchanged after any check, and does not guarantee the availability of any particular specialist, the content of any specialist's opinion, agreement between specialists or any outcome. Composition may change as a matter develops.",
        },
        {
          heading: "7C. Build My Circle",
          body: "A Circle is a bespoke, consent-led set of relationships built around a Member's stated purpose. A Circle may include other Montvelle members, external peers, professionals or organisations who are not members, or a person the Member already knows and asks GSM to bring into the picture. Every introduction requires the consent of the people involved and may be declined without explanation. Being included in a Circle does not make a person a Montvelle member, does not create any membership right and does not grant general access to Montvelle, to other members or to any member information. Circles are not a directory and may not be exported, copied, list-built, marketed to or used for unsolicited prospecting.",
        },
        {
          heading: "7D. External enquiries and the Member's privacy",
          body: "To carry out a request, GSM may make neutral enquiries of external organisations and individuals on the Member's behalf, disclosing only the minimum information necessary to obtain a useful answer. GSM does not disclose the Member's identity, household composition, family circumstances, financial position, health, security arrangements or other private or sensitive details to an external party without the Member's explicit consent, unless disclosure is required by law or by a competent authority. Where a Member prefers to remain unnamed, GSM will make enquiries on an unattributed basis wherever that is practical.",
        },
        {
          heading: "7E. Authority, instructions and spend",
          body: "GSM has no authority to bind the Member, to enter into a contract with a third party for or on behalf of the Member, to accept a third party's terms for the Member, or to incur third-party expenditure, deposits, cancellation exposure or other financial commitment on the Member's account, except to the extent the Member has given express authority or a specific instruction for that matter. Where the Member gives such authority, GSM acts within its stated limits and the resulting third-party contract is between the Member and that third party unless expressly agreed otherwise in writing.",
        },
        {
          heading: "7F. Coordination is not adoption of professional advice",
          body: "GSM coordinates: it holds context, reconciles dependencies between advisers and providers, chases and consolidates communications, sequences work and keeps the Member's overall picture current. GSM may relay, organise, compare or summarise material received from independent advisers for coordination purposes, but doing so does not verify, adopt, endorse or make that professional advice GSM's own. Where an adviser provides original written advice, engagement terms or a formal opinion, that original material — not a Montvelle summary — is the material on which the Member should rely. Coordination does not make GSM the Member's regulated adviser, agent, fiduciary or professional representative in any field and does not transfer to GSM the professional responsibility of any adviser, specialist or provider instructed by the Member.",
        },
        {
          heading: "7G. Decision Rooms and external participants",
          body: "A Decision Room is scoped to a specific matter. Where the Member consents, a selected external adviser or specialist may be associated with that matter and given access limited to the minimum information necessary for it, for as long as the matter requires. External participation never confers access to the Member's wider household record, other matters, other members or the Member's general Montvelle environment, and access may be withdrawn by the Member at any time.",
        },
        {
          heading: "7H. Professional engagements, complaints and claims",
          body: "A lawyer, tax adviser, investment adviser, immigration adviser, doctor, healthcare professional, accountant, private banker, fiduciary or other independent professional remains responsible for advice and services provided under that professional's own engagement. The Member should read and retain the professional's engagement letter, scope, fee terms, complaints process and insurance or regulatory information where relevant. A complaint or claim about professional advice, negligent professional work, breach of professional duty or a regulated service should in the first instance be pursued against the relevant professional under that engagement and any applicable complaints, ombudsman, regulatory or insurance route. GSM may assist with coordination or escalation as a member service, but that assistance does not make GSM jointly liable for the professional's acts or omissions or amount to an admission of liability.",
        },
        {
          heading: "8. Commissions, referrals and conflicts",
          body: "GSM may have preferred commercial relationships with suppliers and may receive commissions, referral fees, rebates, preferred rates, benefits or other consideration. Material arrangements that could reasonably affect a Member's decision will be disclosed where required by law or applicable Montvelle policy. A provider's relationship with GSM does not purchase member identities, visibility inside Montvelle, confidential-room access, listing to members or any right to prospect members.",
        },
        {
          heading: "9. No regulated or professional advice by Montvelle",
          body: "Montvelle is a private membership, community, research, coordination and lifestyle service. GSM is not acting as a law firm, tax adviser, investment adviser, broker-dealer, immigration adviser, healthcare provider, fiduciary, trustee, insurer or other regulated professional merely by providing membership, information, introductions, research or coordination. General materials, peer discussions, software or AI-assisted outputs and operational suggestions are not substitutes for advice from appropriately qualified professionals instructed for the Member's own circumstances. Where a matter requires regulated or licensed advice, the Member must obtain that advice independently and remains responsible for deciding whether, when and how to act on it.",
        },
        {
          heading: "10. Member conduct",
          body: "Members and authorised users must act lawfully, respectfully and consistently with the private nature of Montvelle. Unless expressly authorised, prohibited conduct includes scraping, bulk export, list building, credential sharing, impersonation, doxxing, unauthorised recording or screenshots, unauthorised forwarding, unsolicited commercial prospecting, recruitment poaching, harassment, circumvention of access controls, misuse of confidential information and using Montvelle or member data to train an external model or dataset. A Member must not claim that GSM, Montvelle or another member endorses the Member, an investment, transaction, product or provider without express written authority.",
        },
        {
          heading: "11. Confidentiality and introductions",
          body: "Information shared in a private Table, Decision Room, member-only area, private gathering, concierge request, family context, ownership context, adviser context or confidential communication must be treated as confidential where a reasonable person would understand it to be private. Members may use general learning and ideas from the community but must not identify another person or disclose that person's confidential facts, family circumstances, commercial information or sensitive context without permission. Private sessions may not be recorded, transcribed, photographed, screenshotted, forwarded or published without appropriate consent. Montvelle introductions are consent-led. Confidentiality obligations survive expiry or termination, subject to disclosures required by law or competent authority.",
        },
        {
          heading: "12. Family and under-18 participants",
          body: "A person under 18 may not contract directly with GSM. A parent, guardian or other legally authorised adult must approve any under-18 participation and is responsible for ensuring information provided about a child is lawfully shared. GSM may apply separate age, supervision, account-access, communications, safeguarding and event rules to next-generation programmes and may immediately restrict participation where it reasonably believes safety, welfare, safeguarding or legal compliance is at risk.",
        },
        {
          heading: "13. Privacy and member information",
          body: "GSM processes personal information in accordance with the Montvelle Privacy Notice and applicable law. Member-directory information is private by default. GSM does not sell the member directory or grant third parties unrestricted prospecting access to member identities. The Member grants GSM the limited rights reasonably required to host, process, reproduce and transmit information submitted by or for the Member in order to provide, secure and administer the service, comply with law and exercise GSM's rights under this Agreement. Ownership of a Member's own confidential information remains with the Member or lawful owner.",
        },
        {
          heading: "14. AI-assisted tools",
          body: "GSM may use software and AI-assisted tools to organise information, support research, summarise material, coordinate workflows or surface options. Material membership, safety or similarly significant decisions should include human review where appropriate or legally required. Confidential member content should not be used to train a public or general-purpose model without an appropriate legal basis and any permission required by law or Montvelle policy.",
        },
        {
          heading: "15. Intellectual property",
          body: "GSM or its licensors own the Montvelle name, marks, visual identity, website, software, private frameworks, editorial content and original materials except for material expressly identified as belonging to a Member or third party. During active membership GSM grants the Member a limited, personal, revocable, non-exclusive and non-transferable right to use Montvelle materials for the Member's own private purposes. Montvelle materials may not be reproduced, resold, republished, reverse engineered, commercially exploited or used to create confusingly similar products except to the extent a non-waivable legal right permits it.",
        },
        {
          heading: "16. Availability and changes",
          body: "GSM aims to provide a secure and reliable service but does not guarantee uninterrupted or error-free access. GSM may change features, suppliers, programme formats, locations, digital functionality and operating processes where reasonably necessary for security, legal compliance, capacity, service quality or product development. A routine product update will not be used to remove a material paid contractual right during a current term except in accordance with this Agreement, the Membership Schedule and mandatory law. Temporary unavailability of an individual feature, event, supplier, adviser, destination or communication channel does not by itself amount to withdrawal of the membership where the overall service remains materially available through reasonable alternatives.",
        },
        {
          heading: "17. Compliance, sanctions and prohibited activity",
          body: "GSM may refuse, delay, restrict or terminate a membership, request, payment or introduction where it reasonably believes continuing could breach sanctions, export controls, anti-bribery law, fraud controls, financial-crime obligations, court orders or other applicable law. Montvelle must not be used to facilitate bribery, corruption, money laundering, sanctions evasion, fraud, trafficking, prohibited investment activity or other unlawful conduct. GSM may request information reasonably required to assess a compliance concern and may make disclosures to competent authorities where legally required. Where a payment or refund would itself be prohibited or restricted by sanctions or other law, GSM may withhold or delay it for so long as the restriction applies without being treated as in breach.",
        },
        {
          heading: "18. Suspension and termination",
          body: "GSM may suspend access while investigating a credible security, safety, confidentiality, payment, legal or serious conduct concern. GSM may terminate membership for material or repeated breach, confidentiality or no-solicitation breach, harassment, fraud, unlawful activity, material non-payment, reversed payment, serious safety risk, materially misleading information, sanctions/compliance concerns or conduct that materially threatens the trust, privacy, legal position or integrity of the community. Where GSM terminates for Member breach, fraud, misconduct, non-payment, sanctions/compliance, safety or another reason attributable to the Member, no contractual refund, credit or pro-rata repayment of the annual Membership Fee is due after the cooling-off period, subject always to mandatory law. Where GSM terminates an active membership for convenience without Member fault, the Member's sole contractual fee remedy is the unearned pro-rata portion of the annual Membership Fee from the termination date; admission/onboarding amounts already earned and authorised third-party costs remain excluded to the extent permitted by law. Provisions intended by their nature to survive termination — including confidentiality, intellectual property, accrued payment obligations, liability, dispute and data-related obligations — continue after membership ends.",
        },
        {
          heading: "19. Member responsibility",
          body: "The Member remains responsible for personal, family, commercial, investment, tax, legal, immigration, medical, educational, travel and other decisions. Information obtained through Montvelle may be incomplete, become outdated or reflect another member's personal experience rather than professional advice. The Member must provide materially accurate information where GSM or a third party is asked to act on it, must review important documents and professional advice before acting, and is responsible for ensuring that authorised users comply with this Agreement.",
        },
        {
          heading: "19A. Member indemnity for misuse and third-party claims",
          body: "A business or entity Member indemnifies GSM and its officers, employees and contractors against reasonable losses, liabilities, claims and professional costs arising from that Member's unlawful instruction, material breach of this Agreement, infringement of third-party rights, misuse of the service, materially inaccurate information supplied for GSM or a third party to act upon, or unauthorised activity by a delegate or guest for whom that Member is responsible, except to the extent the loss was caused by GSM's own breach, negligence or other liability that cannot lawfully be excluded. For an individual consumer Member, this clause applies only to the extent permitted by mandatory law and only to loss reasonably caused by that Member's unlawful or deliberately wrongful conduct or material breach.",
        },
        {
          heading: "20. Liability",
          body: "Nothing in this Agreement excludes or limits liability that cannot lawfully be excluded or limited, including liability for fraud or fraudulent misrepresentation and any non-excludable duty to exercise reasonable care and skill where applicable. Subject to those non-excludable liabilities and to the fullest extent permitted by law, GSM is not liable for indirect, incidental, consequential, special, exemplary or punitive loss, or for loss of profit, revenue, business opportunity, goodwill, anticipated savings, investment value or data. Subject to mandatory law, GSM is not liable for the acts, omissions, insolvency, delay, cancellation, negligence, professional negligence, advice, misstatement or non-performance of an independent third-party supplier, adviser or specialist merely because Montvelle sourced, introduced, recommended, checked, coordinated or communicated with that third party. GSM's total aggregate liability for all other losses arising under or in connection with a Membership, whether in contract, tort (including negligence), misrepresentation, breach of statutory duty or otherwise, will not exceed the annual Membership Fee paid or payable to GSM for the relevant 12-month term, unless applicable law requires a higher or different liability position. Claims arising from the same or substantially the same facts, event, instruction, request or connected series of events are treated as one claim for the purpose of that aggregate cap.",
        },
        {
          heading: "20A. Mitigation, recoveries and no double recovery",
          body: "A party claiming loss must take reasonable steps to avoid or reduce that loss. The Member may not recover twice for the same loss. To the extent the Member receives compensation, reimbursement, insurance proceeds, a refund, settlement or another recovery from a supplier, adviser, insurer, card issuer, bank or other third party for the same loss, that recovery will be taken into account in assessing any amount recoverable from GSM. The Member should notify GSM of a material claim as soon as reasonably practicable and provide reasonable information needed to investigate it; a delay in notification affects GSM's position only to the extent GSM is materially prejudiced by that delay.",
        },
        {
          heading: "21. Events outside reasonable control",
          body: "Neither party is responsible for delay or failure in performing an affected obligation to the extent caused by an event outside that party's reasonable control. Such events may include natural disaster, extreme weather, war, terrorism, civil disorder, epidemic or pandemic, government or regulatory action, sanctions, border or travel restrictions, widespread transport disruption, industrial action not limited to that party's own workforce, failure of critical utilities or communications infrastructure, material cloud or telecommunications outage, cyberattack despite reasonable preventative measures, or the sudden closure or failure of a material venue or third-party supplier. The affected party must take reasonable steps to mitigate the effect. GSM may extend timescales, use alternative personnel, suppliers, communications channels or delivery methods, postpone an event or request, or suspend the affected part of the service while the event continues. No compensation is due merely because a particular supplier, destination, event, feature or request is delayed or unavailable where the overall membership remains materially available. Force majeure does not excuse amounts already due, authorised third-party costs, confidentiality obligations or data/security duties that can still reasonably be performed. If substantially all core Montvelle membership services are continuously unavailable for more than 90 days and GSM cannot provide a materially reasonable alternative, either party may end the affected membership. In that exceptional case, the Member's contractual fee remedy is limited to the unearned pro-rata portion of the annual Membership Fee from the termination date; admission/onboarding amounts already earned and non-recoverable third-party costs remain excluded to the extent permitted by law. Mandatory cancellation, refund and consumer rights remain unaffected.",
        },
        {
          heading: "22. Electronic contracting and notices",
          body: "This Agreement and a Membership Schedule may be accepted electronically and in counterparts. Routine membership notices may be sent electronically to the contact details held for the Member. Formal legal notices must be sent using the notice details stated in the Membership Schedule, invoice, Legal Notice or other formal GSM correspondence.",
        },
        {
          heading: "23. Assignment",
          body: "The Member may not assign or transfer this Agreement or membership without GSM's prior written consent. GSM may assign this Agreement to an affiliate, successor or purchaser of substantially all of the relevant business or assets, subject to applicable law and without reducing mandatory Member rights.",
        },
        {
          heading: "24. Entire agreement, severability and waiver",
          body: "The Membership Schedule, this Agreement, the Website Terms, Privacy Notice, Confidentiality & No Solicitation standard and any other document expressly incorporated by the Membership Schedule or this Agreement form the entire agreement for the paid membership relationship and supersede prior statements about that relationship, subject to liability for fraud and non-waivable rights. Where documents conflict, the order of precedence is the Membership Schedule, this Agreement, then the Website Terms unless an expressly incorporated document states a more specific rule for its subject matter or mandatory law requires another result. The Member acknowledges that, except for statements expressly incorporated into those contractual documents, membership is not purchased in reliance on a representation that any particular person, supplier, event, benefit, result, saving or introduction will be available. If a provision is invalid or unenforceable, it will be modified or severed only to the minimum extent necessary and the remaining provisions continue in effect. A failure to enforce a provision is not a waiver of that provision.",
        },
        {
          heading: "25. Relationship of the parties",
          body: "Nothing in the Montvelle relationship creates a partnership, joint venture, employment relationship, fiduciary relationship, agency or authority for one party to bind the other unless a separate written document expressly states otherwise.",
        },
        {
          heading: "26. Governing law and disputes",
          body: "This Agreement is governed by the laws of the State of Delaware, United States, without prejudice to mandatory consumer, privacy or other rights that apply because of the Member's residence or other applicable law. The parties should first attempt in good faith to resolve a dispute directly. Subject to any mandatory local right to bring proceedings elsewhere, the state and federal courts located in Delaware have jurisdiction over disputes arising from this Agreement unless the applicable Membership Schedule expressly provides another lawful dispute process.",
        },
        {
          heading: "27. Language",
          body: "Translations may be provided for convenience. The English-language Agreement is authoritative to the extent permitted by applicable law. Where mandatory local law requires another language or gives a translated version legal priority, that law applies.",
        },
      ]}
    />
  );
}
