import { createFileRoute } from "@tanstack/react-router";
import { LegalTemplate } from "@/components/marketing/LegalTemplate";
import { site } from "@/config/site";

export const Route = createFileRoute("/privacy")({
  head: () => ({ meta: [{ title: `Privacy Notice — ${site.name}` }, { name: "description", content: "How Montvelle and Global Solutions Management LLC handle personal information across applications, membership, requests, gatherings and private services." }] }),
  component: PrivacyPage,
});

function PrivacyPage() {
  return <LegalTemplate title="Privacy Notice" documentKey="privacyNotice" intro={`${site.name} is operated by ${site.operator}, a Delaware limited liability company ("GSM"). We design the service on a privacy-by-default basis: collect what is needed, restrict access by role, use information only for the purpose for which it was entrusted to us, disclose the minimum necessary when acting on a member's behalf, and never treat member identities as a commercial asset.`} sections={[
    { heading: "Who is responsible for your information", body: "For applications, membership administration, the Montvelle environment, request handling, sourcing and coordination, gatherings and our own communications, GSM generally acts as the controller or equivalent responsible business under applicable privacy law. Vendors such as hosting, security, communications and operational technology providers may act as processors where they process personal information on GSM's documented instructions. Other parties with their own legal, regulatory or professional duties — including banks and payment institutions, professional advisers, independent specialists and providers — act as independent controllers for the information they hold and for their own records, and are responsible for their own privacy practices. Where you instruct an external adviser, specialist, firm or provider directly, that organisation is an independent controller for the information you give it." },

    { heading: "Information we may collect", body: "This can include identity and contact details; application and admission information, including the details of the two referees you nominate; professional, ownership and family context you choose to share; preferences and household arrangements; event responses; requests, briefs and Decision Room material; consent-led introduction and Circle context; communications with us; transaction, billing and tax records; device, log, security and usage information; and records needed to protect members and comply with law." },
    { heading: "Sensitive and special-category information", body: "We do not routinely seek sensitive information and we ask you not to volunteer more than a request genuinely requires. Where a request cannot be handled without it — for example health context for a medical arrangement, dietary or accessibility needs, or information about a child — we collect only what is necessary for that specific purpose, restrict access to the people handling it, retain it no longer than needed, and rely on an appropriate lawful condition, which in most cases will be your explicit consent. We do not use sensitive information for marketing or profiling." },
    { heading: "Information we obtain from other people", body: "Some information reaches us indirectly: from the member or applicant who refers or nominates you; from referees asked to give assurance; from an approved household principal describing household arrangements; from public, professional, corporate, regulatory or licensing sources consulted when we research specialists for an Expert Council, build a Circle or carry out due diligence and compliance checks; and from third parties handling a request. Where required, we give people whose information we obtain indirectly the transparency their local law provides — including the categories of information, the source, the purposes and their rights — unless an exemption applies. Sources of this kind are typically the referring person, the person's own public professional profile, or a regulated registry." },
    { heading: "Why we use information, and on what basis", body: "To assess an application and take steps you ask for before a contract: performance of a contract or pre-contractual steps, and legitimate interests in protecting the community. To form and administer a membership, handle requests, source and coordinate external expertise, run Decision Rooms, gatherings and family programmes: performance of the contract. To make consent-led introductions or build a Circle: consent, and legitimate interests in operating a private community. To research specialists and providers on your behalf: legitimate interests, and consent where identity or private context would be disclosed. To protect members, prevent misuse, fraud and security incidents, and maintain records: legitimate interests and legal obligation. To meet accounting, tax, sanctions, anti-bribery and other statutory duties: legal obligation. For special-category information: explicit consent or another lawful condition. Consent can be withdrawn at any time without affecting earlier lawful processing." },
    { heading: "Request-led service and external enquiries", body: "There is no member-facing directory of providers and we do not publish or share member profiles with providers. When we make enquiries on your behalf, we disclose the minimum information necessary to obtain a useful answer and, wherever practical, we do so without naming you. Your identity, household composition, family circumstances, financial position, health, security arrangements and other private details are not disclosed to an external party without your explicit consent, unless disclosure is required by law or a competent authority." },
    { heading: "Community, introductions and Circles", body: "Member profiles are restricted to authorised member areas. Contact details are hidden by default. Member information must not be sold, scraped, bulk-exported, supplied to sponsors or used for unsolicited prospecting, and we do not permit it. Before any introduction, we confirm both sides are willing; private contact details and sensitive context are released only after that consent. A person included in a Circle who is not a member receives no access to Montvelle or to other members." },
    { heading: "Household access and privacy between adults", body: "Each approved adult in a household has their own login. An adult household member's own requests, messages and private matters are not automatically visible to the household principal or to other household users; sharing happens only where that person chooses it or the Membership Schedule provides for it. A household delegate sees only the specific matters they have been asked to handle." },
    { heading: "Children and next-generation participation", body: "A person under 18 cannot contract with GSM. Any under-18 participation in Montvelle requires the authority of a parent, guardian or other legally responsible adult, and access is age-appropriate and supervised: next-generation participation is limited to material and activities suitable for that person, and does not extend to adult financial, commercial, security or other private household matters. There are no unrestricted child accounts. We collect the minimum information needed for a child's participation and safety, apply stricter access and safeguarding controls, and never use children's information for behavioural advertising or sell it. A parent or guardian may withdraw participation at any time." },
    { heading: "Who we share information with", body: "We disclose information only where reasonably necessary to operate the service, complete a request you have authorised, protect members, process payments, host or secure systems, deliver communications, obtain our own professional advice, or comply with law. Processors handling Montvelle information are bound by contractual confidentiality, security and use restrictions. Independent controllers — including advisers, specialists, providers and our bank — are responsible for their own handling of information you or we lawfully pass to them for a request you have authorised." },
    { heading: "International transfers", body: "Montvelle serves an international membership and our providers and specialists may operate in more than one country, so information may be transferred outside your country of residence. Where a transfer is subject to a restricted-transfer regime, we rely on the safeguards recognised by that law — an adequacy decision, standard contractual clauses or equivalent approved terms, or a permitted derogation such as your explicit consent or necessity for a contract you have asked us to perform. Details of the safeguard applied to a particular transfer are available on request." },
    { heading: "How long we keep information", body: "We retain information only as long as needed for the purpose it was collected for, then delete, anonymise or securely archive it. As a guide: unsuccessful applications and their referee details are kept for a limited period to evidence the decision and prevent duplicate approaches; membership records, contracts and acceptance evidence are kept for the membership and for the period needed for legal claims and statutory records; financial and tax records are kept for the statutory period; request, sourcing and Decision Room material is kept for the matter and a reasonable review period afterwards; security and access logs are kept for a short operational period; sensitive information is kept for the shortest period the matter allows. Where law requires longer retention, that requirement prevails." },
    { heading: "Security", body: "We use role-based access, authentication, least-privilege permissioning, scoped matter access, secure storage, vendor oversight and other technical and organisational measures appropriate to the sensitivity of the information involved. No online service can promise absolute security; suspected material incidents are assessed and notified where applicable law requires it." },
    { heading: "Your rights, verification and complaints", body: "Depending on where you live, you may have rights to access, correct, delete, restrict or object to processing; to withdraw consent; to receive certain information in portable form; to opt out of marketing or of certain sharing; and not to be discriminated against for exercising a right. Because Montvelle handles private household information, we verify identity before acting on a request and may ask for further detail; we do not disclose one household member's private matters to another. We respond within the period your law requires. If you are unhappy with our response you may ask us to review it, and you may also complain to the data-protection or privacy authority in your country or region. Use the Contact Montvelle route below to make a request, appeal a decision or serve a formal privacy notice." },
    { heading: "AI-assisted tools and automated decisions", body: "We may use software and AI-assisted tools to organise information, support research, summarise material and coordinate workflows. Confidential member content is not used to train public or general-purpose models without a lawful basis and any permission required by law or Montvelle policy. We do not intend to make solely automated decisions producing legal or similarly significant effects without the safeguards your law requires; material membership, admission, safeguarding and similarly significant decisions receive human review." },
    { heading: "Translation and third-party links", body: "The language selector uses the Google Translate widget to translate the public pages in your browser. When you select a language, Google processes the page content under its own terms and privacy practices. Other external links and independently provided services are governed by the third party's own privacy terms. The English-language Montvelle documents remain authoritative." },
    { heading: "Changes to this notice", body: "We may update this notice as the service, the law or our providers change, and material changes are communicated appropriately. The version and date of the current notice are shown on this page." },
  ]} />;
}
