import { createFileRoute } from "@tanstack/react-router";
import { LegalTemplate } from "@/components/marketing/LegalTemplate";
import { site } from "@/config/site";

export const Route = createFileRoute("/privacy")({
  head: () => ({ meta: [{ title: `Privacy — ${site.name}` }, { name: "description", content: "How Montvelle and Global Solutions Management LLC handle personal information across applications, membership, concierge, gatherings and private services." }] }),
  component: PrivacyPage,
});

function PrivacyPage() {
  return <LegalTemplate title="Privacy" intro={`Last updated 22 August 2026. ${site.name} is operated by ${site.operator}, a Delaware limited liability company. We design the service on a privacy-by-default basis: collect what is needed, restrict access, use information for the purpose for which it was entrusted to us, and do not turn the member directory into a commercial asset.`} sections={[
    { heading: "Who is responsible for your information", body: "For applications, membership administration, the Montvelle platform, concierge coordination and our own communications, Global Solutions Management LLC generally acts as the controller or equivalent responsible business under applicable privacy law. A Trusted Partner or other independently instructed professional may be a separate controller for information you provide directly to them." },
    { heading: "Information we may collect", body: "This can include identity and contact details; application and membership information; professional and family context you choose to share; preferences; event responses; concierge and introduction requests; communications; transaction and billing records; device, security and usage information; and records needed to protect the community. We do not ask for sensitive family, financial, medical, biometric or identity documents unless they are genuinely required for a specific service and an appropriate secure process is in place." },
    { heading: "Why we use it", body: "We use information to assess applications; form and administer memberships; operate Tables, gatherings, family programmes and private-office services; answer requests; make consent-led introductions; protect members and the platform; prevent misuse and fraud; meet legal obligations; maintain records; improve the service; and, where permitted, communicate relevant Montvelle news or invitations." },
    { heading: "Legal bases and permissions", body: "Depending on your location, processing may rely on performance of a contract or steps requested before a contract, legitimate interests, compliance with legal obligations, protection of vital or community interests, or consent. Where consent is the appropriate basis, it can be withdrawn without affecting earlier lawful processing. Mandatory rights under local privacy and consumer law are not excluded by these terms." },
    { heading: "Member directory and introductions", body: "Member profiles are restricted to authorised community areas. Contact details are hidden by default unless a member chooses to share them. Directory information must not be sold, scraped, bulk-exported, supplied to sponsors or used for unsolicited prospecting. Concierge may use enough context to assess whether an introduction is relevant, but private contact details or sensitive case context should not be released to another member or Trusted Partner until the member has agreed to that connection." },
    { heading: "Family and next generation", body: "Information about children and under-18 participants is subject to stricter access and safeguarding boundaries. We seek appropriate guardian permissions, limit visibility and access by role, and do not give under-18s unmanaged access to adult confidential member spaces. We do not knowingly use children's information for behavioural advertising or sell it." },
    { heading: "Trusted Partners and service providers", body: "We may disclose information only where reasonably necessary to operate the service, complete a request you have authorised, protect the community, process payments, host or secure systems, deliver communications, obtain professional advice or comply with law. We expect vendors handling Montvelle information to be subject to appropriate contractual, confidentiality and security obligations. Independently instructed legal, tax, immigration, medical, fiduciary, investment and other regulated professionals are responsible for their own professional relationship with you." },
    { heading: "International transfers", body: "Montvelle is designed for an international membership and our providers or professionals may operate in more than one country. Where personal information is transferred across borders, we use the safeguards required by applicable law where they apply, which may include adequacy decisions, contractual protections or other recognised transfer mechanisms. Local mandatory rights remain unaffected." },
    { heading: "Retention", body: "We keep information only for as long as reasonably needed for the relevant membership, application, request, safety, accounting, dispute, regulatory or legal purpose. Different categories may have different retention periods. When information is no longer required, it should be deleted, anonymised or securely archived where law requires continued retention." },
    { heading: "Security", body: "We use role-based access, authentication, permissioning, secure storage, audit controls, vendor oversight and other technical and organisational measures appropriate to the sensitivity of the information involved. No online service can promise absolute security; suspected material incidents are assessed and notified where applicable law requires it." },
    { heading: "Your rights", body: "Depending on where you live, you may have rights to access, correct, delete, restrict or object to processing; withdraw consent; receive certain information in portable form; opt out of certain marketing; or appeal a privacy decision. We may need to verify identity and may retain information where law or legitimate legal claims require it. Requests can be made through the contact route supplied in your application or membership correspondence." },
    { heading: "Automated decisions and AI-assisted tools", body: "Montvelle may use software or AI-assisted tools to organise information, prepare summaries, surface relevant options or support operational workflows. We do not intend to make solely automated decisions that produce significant legal or similarly significant effects on a person without the safeguards required by applicable law. Material membership, safeguarding or high-impact decisions should include human review." },
    { heading: "Translation and third-party links", body: "The language selector may send the current public page to Google Translate when you choose a non-English language. Google then processes that request under its own terms and privacy practices. Other external links and independently provided services are governed by the third party's own privacy terms. The English-language Montvelle documents remain authoritative." },
    { heading: "Changes and questions", body: "We may update this notice as the service, law or our providers change. Material changes should be communicated appropriately. Privacy questions, complaints or rights requests can be raised through the contact route in your Montvelle application or membership correspondence; you may also have the right to complain to the data-protection authority in your country or region." },
  ]} />;
}
