import { createFileRoute } from "@tanstack/react-router";
import { LegalTemplate } from "@/components/marketing/LegalTemplate";
import { site } from "@/config/site";

export const Route = createFileRoute("/terms")({
  head: () => ({ meta: [{ title: `Terms — ${site.name}` }, { name: "description", content: "Terms governing Montvelle website access, membership, community spaces, payment and private services operated by Global Solutions Management LLC." }] }),
  component: TermsPage,
});

function TermsPage() {
  return <LegalTemplate title="Terms of membership & use" intro={`Last updated 23 August 2026. Montvelle is a brand and service operated by ${site.operator}, a Delaware limited liability company ("GSM"). These website terms apply to the public and member-facing Montvelle service unless a separate Membership Agreement, Membership Schedule, order form or service agreement expressly provides otherwise. For a paid membership, the signed or electronically accepted Membership Agreement and Membership Schedule prevail to the extent of any conflict.`} sections={[
    { heading: "Eligibility, payment and acceptance", body: "Montvelle is a private membership. A person may be able to submit details and pay the displayed first-year fees through our secure payment provider, but payment does not compel GSM to admit a person or override identity, sanctions, fraud, safety, suitability or compliance checks. Membership activates only when GSM has accepted the membership, applicable contractual documents have been accepted, required checks are complete and cleared funds have been confirmed. If GSM declines an unactivated membership after payment, GSM will arrange return of membership and admission fees paid for that unaccepted membership, subject to applicable law and any payment-provider reversal process." },
    { heading: "Published fees and future pricing", body: "The website may display the current standard annual membership fee and any admission or onboarding fee. The amount shown at checkout, on the invoice or in the Membership Schedule is the contractual price for that purchase. Membership is ordinarily for 12 months and paid in advance. GSM may change prices for future new memberships and renewals. A renewal is charged at the price stated in the renewal invitation or Membership Schedule, with notice provided as required by the applicable agreement and law. Nothing on the website guarantees a future or grandfathered price." },
    { heading: "Cancellation, cooling-off and refunds", body: "Cancellation and refund rights depend on the member's contracting capacity, location, the Membership Agreement and mandatory law. Where a statutory cooling-off right applies, it is not excluded. If a member expressly asks GSM to begin onboarding or services during a statutory cancellation period, GSM may deduct the value of services already supplied where applicable law permits. Admission/onboarding work, third-party charges and non-refundable supplier costs are treated in accordance with the Membership Agreement and mandatory law." },
    { heading: "Account security", body: "Credentials and private materials must be kept confidential and used only by authorised people. Members are responsible for activity carried out through their account unless they promptly report suspected compromise. GSM may require additional authentication or temporarily restrict access where security or confidentiality is at risk." },
    { heading: "Community services", body: "Membership may include peer Tables, gatherings, introductions, knowledge, Decision Rooms, Global Life coordination, Concierge, family learning, Trusted Partner access and other services made available to the applicable membership relationship. Availability can vary by programme, geography, capacity, legal restrictions and the specific commercial terms agreed with the member. No particular event, reservation, introduction, provider, location or outcome is guaranteed." },
    { heading: "Third-party costs and payment", body: "Hotels, transport, venues, schools, restaurants, healthcare providers, advisers, property providers and other third parties may charge separately and impose their own terms, deposits and cancellation policies. Unless expressly stated in writing, these charges are not included in Montvelle membership fees. Members are responsible for taxes, duties, levies, bank charges and other amounts legally due in connection with their purchase. GSM may suspend services for overdue, reversed, disputed or declined amounts where lawful." },
    { heading: "No guaranteed outcome", body: "Montvelle is designed to improve access, judgement, relationships, coordination and the quality of private life. It does not guarantee clients, funding, investment returns, transactions, introductions, reservations, upgrades, school places, visas, immigration outcomes, medical outcomes, professional results or any other commercial or personal result." },
    { heading: "Professional and regulated advice", body: "Montvelle and GSM are not acting as a law firm, investment adviser, broker-dealer, tax adviser, medical provider, immigration adviser, fiduciary, trustee or other regulated professional practice merely by providing membership, introductions, information, research or coordination. Community discussions, software outputs and educational materials are not substitutes for advice from an appropriately qualified professional instructed for the member's own circumstances." },
    { heading: "Introductions, suppliers and commissions", body: "An introduction, directory listing, invitation or availability of a Trusted Partner is not a warranty of that person's advice, conduct, licensing, availability or outcome. Unless GSM expressly contracts as the supplier, the member's contract for a third-party product or professional service is with that supplier and the member remains responsible for appropriate due diligence. GSM may have preferred commercial relationships or receive commissions, referral fees, rebates, benefits or other consideration from suppliers. Material arrangements will be disclosed where required by law or applicable Montvelle policy." },
    { heading: "Conduct and confidentiality", body: "Members, applicants, partners and guests must respect confidentiality, consent, safeguarding, anti-harassment standards, lawful behaviour and the privacy of other people. Scraping, bulk exporting, unauthorised recording, doxxing, unsolicited prospecting, impersonation, credential sharing, circumvention of access controls and misuse of confidential member information are prohibited. Serious or repeated breaches may lead to restricted access, suspension or termination." },
    { heading: "Family and safeguarding", body: "A person under 18 may not contract directly with GSM. Access involving children or under-18 participants is subject to appropriate parent or guardian authority, age-appropriate permissions and safeguarding controls. GSM may restrict or stop activity where it reasonably believes safety, welfare or legal compliance is at risk." },
    { heading: "Content and intellectual property", body: "The Montvelle name, marks, site design, editorial material, software, private frameworks and original content are owned by or licensed to GSM unless stated otherwise. Members receive only the limited right needed to use the service under their membership. Private materials may not be copied, republished, reverse engineered, commercially exploited or used to train external models without permission, except where law gives a non-waivable right." },
    { heading: "Technology and availability", body: "GSM aims to provide a secure and reliable service but does not promise uninterrupted or error-free availability. GSM may maintain, update, suspend or change features where reasonably necessary for security, law, service quality, capacity or product development. Material changes to paid contractual rights during a current term are governed by the applicable Membership Agreement and mandatory law." },
    { heading: "Compliance, sanctions and prohibited activity", body: "GSM may refuse, delay, restrict or terminate a membership, request, payment or introduction where it reasonably believes continuing could breach sanctions, export controls, anti-bribery law, fraud controls, financial-crime obligations, court orders or other applicable law. Montvelle must not be used to facilitate bribery, corruption, money laundering, sanctions evasion, fraud or other unlawful conduct." },
    { heading: "Suspension and termination", body: "GSM may restrict or end access where terms are breached, fees remain unpaid, payment is reversed, fraud or misuse is suspected, safety or confidentiality is at risk, law requires action, or continued membership would materially threaten the trust, privacy, legal position or integrity of the community. Where appropriate and lawful, significant membership decisions should receive human review. The financial consequences of termination are governed by the Membership Agreement, the circumstances and mandatory law." },
    { heading: "Liability", body: "Nothing in these website terms excludes liability that cannot legally be excluded, including liability for fraud or other non-excludable matters. Liability arising from paid membership is governed primarily by the applicable Membership Agreement. Subject to mandatory law, GSM is not responsible for an independent supplier's acts or omissions merely because Montvelle introduced or coordinated that supplier. The public website and general information are provided on an as-available basis and users remain responsible for their own decisions." },
    { heading: "Events outside reasonable control", body: "Neither party is responsible for delay or failure caused by events outside its reasonable control to the extent permitted by law, including natural disasters, war, terrorism, civil disruption, epidemic or pandemic restrictions, government action, transport disruption, widespread communications outages or supplier failures. Mandatory refund and consumer rights remain unaffected." },
    { heading: "Governing law and mandatory local rights", body: "Unless a separate Membership Agreement states otherwise, these website terms are governed by the laws of the State of Delaware, United States, without prejudice to mandatory consumer, privacy or other rights that apply because of a user's place of residence or other applicable law. The paid Membership Agreement may specify a dispute process or forum for the particular relationship." },
    { heading: "Language and changes", body: "Translations are provided for convenience. The English-language version is authoritative to the extent permitted by applicable law. GSM may update website terms and operational policies as the service, law or risk environment changes. Material changes to an active paid membership are handled in accordance with the Membership Agreement and applicable law." },
  ]} />;
}
