import { createFileRoute } from "@tanstack/react-router";
import { LegalTemplate } from "@/components/marketing/LegalTemplate";
import { site } from "@/config/site";

export const Route = createFileRoute("/terms")({
  head: () => ({ meta: [{ title: `Terms — ${site.name}` }, { name: "description", content: "Terms governing Montvelle website access, membership, community spaces and private services operated by Global Solutions Management LLC." }] }),
  component: TermsPage,
});

function TermsPage() {
  return <LegalTemplate title="Terms of membership & use" intro={`Last updated 22 August 2026. Montvelle is operated by ${site.operator}, a Delaware limited liability company. These website terms apply to use of the public and member-facing Montvelle service unless a separate written membership agreement, order form or service agreement expressly provides otherwise. Where there is a conflict, the signed agreement for that relationship prevails.`} sections={[
    { heading: "Eligibility and membership", body: "Montvelle is a private membership community. Membership is by application, invitation and approval. We may request information reasonably needed to assess fit, protect the community, verify identity or satisfy legal and compliance requirements. Membership is personal to the approved person, family or entity identified in the applicable agreement and may not be transferred without written approval." },
    { heading: "Account security", body: "Credentials and private materials must be kept confidential and used only by authorised people. Members are responsible for activity carried out through their account unless they promptly report suspected compromise. Montvelle may require additional authentication or temporarily restrict access where security or confidentiality is at risk." },
    { heading: "Community services", body: "Membership may include peer Tables, gatherings, introductions, knowledge, Decision Rooms, Global Life coordination, Concierge, family learning, Trusted Partner access and other services made available to the relevant membership relationship. Availability can vary by programme, geography, capacity, legal restrictions and the specific commercial terms agreed with the member." },
    { heading: "Fees, taxes and renewals", body: "Membership fees, payment timing, renewal terms, cancellation rights, taxes and service-specific charges are set out in the applicable commercial terms. Members are responsible for taxes or charges legally due in connection with their purchase unless the agreement states otherwise. Mandatory cancellation or consumer rights that apply in a member's location are not excluded." },
    { heading: "No guaranteed outcome", body: "Montvelle is designed to improve access, judgement, relationships, coordination and the quality of private life. It does not guarantee clients, funding, investment returns, transactions, introductions, reservations, school places, visas, immigration outcomes, medical outcomes, professional results or any other commercial or personal result." },
    { heading: "Professional and regulated advice", body: "Montvelle and Global Solutions Management LLC are not acting as a law firm, investment adviser, broker-dealer, tax adviser, medical provider, immigration adviser, fiduciary or other regulated professional practice merely by providing membership, introductions, information or coordination. Community discussions, tools and educational materials are not substitutes for advice from an appropriately qualified professional instructed for your own circumstances." },
    { heading: "Introductions and Trusted Partners", body: "An introduction, directory listing, invitation or availability of a Trusted Partner is not a guarantee, warranty or endorsement of that person's advice, conduct, availability, licensing or outcome. Members decide whether to engage or transact with another person and remain responsible for their own due diligence and contractual relationship. Any material referral or commercial arrangement that could affect a recommendation should be disclosed." },
    { heading: "Travel, events and third-party services", body: "Hotels, transport, venues, schools, restaurants, healthcare providers, advisers, property providers and other third parties may impose their own terms, eligibility rules, deposits, cancellation policies and safety requirements. Unless expressly stated in writing, Montvelle is not the provider of those third-party services and is not responsible for their acts or omissions beyond liabilities that cannot lawfully be excluded." },
    { heading: "Conduct and confidentiality", body: "Members, applicants, partners and guests must respect confidentiality, consent, safeguarding, anti-harassment standards, lawful behaviour and the privacy of other people. Scraping, bulk exporting, unauthorised recording, doxxing, unsolicited prospecting, impersonation, credential sharing, circumvention of access controls and misuse of confidential member information are prohibited. Serious or repeated breaches may lead to restricted access, suspension or termination." },
    { heading: "Family and safeguarding", body: "Access involving children or under-18 participants is subject to age-appropriate permissions and safeguarding controls. Adults must not use Montvelle to bypass parental, guardian, school, venue or professional safeguards. We may restrict or stop activity where we reasonably believe safety, welfare or legal compliance is at risk." },
    { heading: "Content and intellectual property", body: "The Montvelle name, mark, site design, editorial material, software, private frameworks and original content are owned by or licensed to Global Solutions Management LLC unless stated otherwise. Members receive only the limited right needed to use the service under their membership. Private materials may not be copied, republished, reverse engineered, commercially exploited or used to train external models without permission, except where law gives a non-waivable right." },
    { heading: "Technology and availability", body: "We aim to provide a secure and reliable service but do not promise uninterrupted or error-free availability. We may maintain, update, suspend or change features where reasonably necessary for security, law, service quality or product development. Material changes to paid contractual rights should be handled under the applicable membership agreement rather than hidden in routine product updates." },
    { heading: "Suspension and termination", body: "Access may be restricted or ended where terms are breached, fees remain unpaid, fraud or misuse is suspected, safety or confidentiality is at risk, law requires action, or continued membership would materially damage the community. Where appropriate and lawful, significant membership decisions should receive human review. Consequences for prepaid fees or ongoing obligations are governed by the applicable membership agreement and mandatory law." },
    { heading: "Liability", body: "Nothing in these terms excludes liability that cannot legally be excluded, including liability for fraud or other non-excludable matters. Subject to that, liability arising from paid membership is governed primarily by the applicable membership agreement. For free public website use, the site and general information are provided on an as-available basis and users remain responsible for decisions made in reliance on third-party or general informational content." },
    { heading: "Events outside reasonable control", body: "Neither party is responsible for delay or failure caused by events outside its reasonable control to the extent permitted by law, including natural disasters, war, civil disruption, government action, transport failure, widespread communications outages, supplier failures or other force-majeure events. This does not remove payment or refund rights that applicable law makes mandatory." },
    { heading: "Governing law and mandatory local rights", body: "Unless a separate written agreement states otherwise, these website terms are governed by the laws of the State of Delaware, United States, without prejudice to mandatory consumer, privacy or other rights that apply because of a user's country of residence. The applicable membership agreement may specify a different dispute process or forum for the particular relationship." },
    { heading: "Language and changes", body: "Translations are provided for convenience. The English-language version is authoritative to the extent permitted by applicable law. We may update these website terms from time to time; material contractual changes to an active paid membership should be communicated in accordance with the applicable membership agreement." },
  ]} />;
}
